name: negentropia_home
description: Negentropia home in Dart
dependencies:
  benchmark_harness: any
  browser: any
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  stats: any
  vector_math:
    git: https://github.com/johnmccutchan/vector_math.git
  obj:
    git: https://github.com/udhos/obj
